[project]
name = "sermons"
version = "0.1.0"
description = "Reduce the amount of manual work in the recording upload process"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit==4.5.1",
    "pyinstaller==6.18.0",
    "pytest==9.0.2",
    "pytest-cov==6.0.0",
]

[tool.uv]
package = false
